### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by Olegf13** [guiguiboy/PHP-CLI-Progress-Bar#13]
Please make a release of your library for not to add `dev-master` as version constraint to composer.json dependency.

**Comment by madeindjs** [comment]
Same issue. I can't install library with:

    $ composer require --dev guiguiboy/php-cli-progress-bar dev-master

I have to add  `dev-master` like this

     $ composer require --dev guiguiboy/php-cli-progress-bar dev-master

So this produce a `dev-master` dependency

```
{
    "require-dev": {
        "guiguiboy/php-cli-progress-bar": "dev-master"
    }
}
```

**Comment by sadortun** [comment]
@guiguiboy  can you add a release ?

**Comment by sadortun** [comment]
@guiguiboy it look like the composer integration is not updating packagist.org. 

Your tag 1.0 has not been fetched

https://packagist.org/packages/guiguiboy/php-cli-progress-bar

**Comment by guiguiboy** [comment]
Hello all,
release 0.0.4 has just ben created so that you can avoid relying on dev-master in your composer.json.
