### ISSUE TITLE
Display transfer rate

### ISSUE THREAD

**Issue by amercier** [guiguiboy/PHP-CLI-Progress-Bar#2]
Would be a nice feature to add

**Comment by guiguiboy** [comment]
Could you please precise what you mean with display transfer rate ?

**Comment by amercier** [comment]
Well, my bad. I forgot your progress bar is not necessarily related to some "transfer". Your progress bar can be used in various use case:
1. uploading/downloading something
2. reading/writing something
3. progress of a task (ex: copy of 10000 files)
4. state of a stopped task (ex: status of a project version, 100 bugs fixed over 1000)
5. and many, many more...

The only common thing is that  numbers represent the progress: done, total.

In most of the case (not all of them), time is involved (see 1, 2, 3). In some of those case (1, 2), it could be interesting to know the progress rate.

What I suggest is to add an options (true|false=default) to display the progress rate. Implementation could be tricky though. One of the simplest could be:
- on update, if last value/time exists
  - display rate = (last value - given value) / (current time - last update time)
  - set last value = given value
  - set last update time = current time
